const {execSync}=require('child_process'); const fs=require('fs');
const lee=(r)=>JSON.parse(execSync('git show '+r+':src/data/release-notes.json',{encoding:'utf8',maxBuffer:1e8}));
const porV=new Map();
for(const n of lee('HEAD')) porV.set(n.v,n);
for(const n of lee(process.argv[2])) if(!porV.has(n.v)) porV.set(n.v,n);
const cmp=(a,b)=>{const A=a.split('.').map(Number),B=b.split('.').map(Number);
  for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0; if(x!==y) return y-x;} return 0;};
const t=[...porV.values()].sort((a,b)=>cmp(a.v,b.v));
fs.writeFileSync('src/data/release-notes.json',JSON.stringify(t,null,1),'utf8');
console.log('  notas: '+t.length+' · '+t.slice(0,4).map(x=>x.v).join(' · '));
